# Generated by Django 4.0.4 on 2022-04-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formGenerator', '0003_forms_required_alter_forms_parentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='formName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='forms',
            name='parentID',
            field=models.CharField(default=53479842, max_length=500),
        ),
    ]
