# Generated by Django 4.0.4 on 2022-04-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formGenerator', '0004_forms_formname_alter_forms_parentid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentID', models.CharField(max_length=500)),
                ('fieldName', models.CharField(max_length=500)),
                ('fieldData', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='forms',
            name='parentID',
            field=models.CharField(default=44310236, max_length=500),
        ),
    ]
