# Generated by Django 4.0.4 on 2022-04-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formGenerator', '0006_mainform_alter_forms_parentid_forms_formparent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='parentID',
            field=models.CharField(default=41734308, max_length=500),
        ),
        migrations.AlterField(
            model_name='mainform',
            name='InviteKey',
            field=models.TextField(default='Zec9i45DcxF5zXKXKHctgN'),
        ),
    ]
