# Generated by Django 4.0.4 on 2022-04-16 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formGenerator', '0007_alter_forms_parentid_alter_mainform_invitekey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formstore',
            name='parentID',
        ),
        migrations.AddField(
            model_name='formstore',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='formGenerator.mainform'),
        ),
        migrations.AlterField(
            model_name='forms',
            name='parentID',
            field=models.CharField(default=37133293, max_length=500),
        ),
        migrations.AlterField(
            model_name='mainform',
            name='InviteKey',
            field=models.TextField(default='EhKMX9C3AqnkEnUFJqQUYN'),
        ),
    ]
