# Generated by Django 4.0.4 on 2022-04-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formGenerator', '0008_remove_formstore_parentid_formstore_form_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forms',
            name='parentID',
        ),
        migrations.AlterField(
            model_name='mainform',
            name='InviteKey',
            field=models.TextField(default='izPwUFPxw23n8Dk7Psjgqi'),
        ),
    ]
