# Generated by Django 4.0.4 on 2022-04-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formGenerator', '0009_remove_forms_parentid_alter_mainform_invitekey'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='is_selectable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mainform',
            name='InviteKey',
            field=models.TextField(default='M6XpCQ4Hb93S7x7qZZmYEC'),
        ),
    ]
