# Generated by Django 4.0.4 on 2022-04-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formGenerator', '0010_forms_is_selectable_alter_mainform_invitekey'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='mainform',
            name='InviteKey',
            field=models.TextField(default='oJEBifDMRv2JRFYECD3ajM'),
        ),
        migrations.AddField(
            model_name='forms',
            name='options',
            field=models.ManyToManyField(related_name='select_field', to='formGenerator.selectoptions'),
        ),
    ]
