# Generated by Django 4.0.4 on 2022-04-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formGenerator', '0011_selectoptions_alter_mainform_invitekey_forms_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='selectLabel',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='mainform',
            name='InviteKey',
            field=models.TextField(default='MfMPRAYqPVmfhXV4W6pTAs'),
        ),
    ]
