# Generated by Django 4.0.4 on 2022-04-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formGenerator', '0012_forms_selectlabel_alter_mainform_invitekey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forms',
            name='selectLabel',
        ),
        migrations.AddField(
            model_name='forms',
            name='is_notselectable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mainform',
            name='InviteKey',
            field=models.TextField(default='3MnNosRxSkkDubbPULDXSf'),
        ),
    ]
