# Generated by Django 4.0.4 on 2022-04-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formGenerator', '0014_remove_forms_is_notselectable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255)),
                ('disable', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='mainform',
            name='InviteKey',
            field=models.TextField(default='NooFbqgKsZpUAPFZ3LcBGi'),
        ),
    ]
