# Generated by Django 4.0.4 on 2022-04-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formGenerator', '0015_states_alter_mainform_invitekey'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainform',
            name='states',
            field=models.ManyToManyField(to='formGenerator.states'),
        ),
        migrations.AlterField(
            model_name='mainform',
            name='InviteKey',
            field=models.TextField(default='musmZJcjwETVyhvnErR9jX'),
        ),
    ]
